### ISSUE TITLE
Services with "." in name

### ISSUE THREAD

**Issue by kkleidal** [hashicorp/consul-haproxy#19]
I'm using Micro where the convention is to have .'s in the Consul service name.  This naming scheme is incompatible with the backend naming regex defined here:

https://github.com/hashicorp/consul-haproxy/blob/master/main.go#L26

I think changing the regex to:
```
^([^=]+)=([^.]+\.)?(?:([^.:@]+)|'([^']+)')(@[^.:]+)?(:[0-9]+)?$
```
would fix my problem, but I haven't tested it yet.

I will fork the repository for my own use case if you do not think this change is applicable or safe, but if you think it is a good idea, I can make the change, test it, and submit a PR.

**Comment by sethvargo** [comment]
Hi @kkleidal 

This project is deprecated and no longer maintained. Please direct all issues to Consul Template instead.
